#pragma once
// nsrds_functions.cuh -- the NSRDS correlation forms OpenFOAM's liquidProperties are built from.
//
// WHAT THESE ARE. OF's liquid thermophysical properties are not constants and not a perfect gas: each
// of rho, mu, kappa, Cp and h is a temperature correlation, and the correlation FORM differs per
// property. `properties liquid` in thermoType selects this path (constant/thermophysicalProperties in
// the squareBendLiq tutorial), where there is no equationOfState, no transport and no thermo entry at
// all -- those keys are replaced by a named substance whose coefficients OF carries in source.
//
// TRANSCRIBED FROM OF, NOT DERIVED. Each f() below is verbatim from
// src/thermophysicalModels/thermophysicalProperties/lnInclude/NSRDSfunc*.H:
//
//   NSRDSfunc0::f   return ((((f_*T + e_)*T + d_)*T + c_)*T + b_)*T + a_;
//   NSRDSfunc1::f   return exp(a_ + b_/T + c_*log(T) + d_*pow(T, e_));
//   NSRDSfunc5::f   return a_/pow(b_, 1 + pow(1 - T/c_, d_));
//
// The Horner nesting in func0 is OF's own, kept rather than rewritten as a sum of powers: the two are
// not bit-identical in floating point, and the whole point of this file is to reproduce OF's numbers.
//
// The `scalar p` first argument OF's f() takes is unused for every form here (these liquids are treated
// as pressure-independent), so it is omitted rather than carried as a dead parameter.
//
// Tested in tests/test_nsrds.cu against a table generated by OpenFOAM ITSELF (dissect/liqref), not
// against hand arithmetic -- so the test covers the coefficient values and the function forms together
// and fails if either drifts.

#include "cf_types.cuh"

namespace brae {

// NSRDSfunc0: 5th-order polynomial. Used for kappa(T), Cp(T) and h(T).
BRAE_HD inline scalar nsrdsFunc0(
    scalar a, scalar b, scalar c, scalar d, scalar e, scalar f,
    scalar T)
{
    return ((((f*T + e)*T + d)*T + c)*T + b)*T + a;
}

// NSRDSfunc1: exp(a + b/T + c*ln(T) + d*T^e). Used for mu(T).
BRAE_HD inline scalar nsrdsFunc1(
    scalar a, scalar b, scalar c, scalar d, scalar e,
    scalar T)
{
    return exp(a + b/T + c*log(T) + d*pow(T, e));
}

// NSRDSfunc5: a / b^(1 + (1 - T/c)^d). Used for rho(T).
BRAE_HD inline scalar nsrdsFunc5(
    scalar a, scalar b, scalar c, scalar d,
    scalar T)
{
    return a/pow(b, 1 + pow(1 - T/c, d));
}

// ---------------------------------------------------------------------------------------------------
// H2O, verbatim from liquidProperties/H2O/H2O.C. One substance for now because that is what
// squareBendLiq (and squareBendLiqNoNewtonian, whose thermophysicalProperties is byte-identical) asks
// for; the shape generalises to a table when a second liquid appears.
//
// h_ is the analytic INTEGRAL of Cp_ -- its 2nd coefficient equals Cp_'s 1st, its 3rd is Cp_'s 2nd/2,
// and so on -- so h(T) must come from the h_ row and NOT from Cp*(T - Tref). Getting that wrong gives a
// plausible enthalpy that is inconsistent with the heat capacity, which is exactly the failure the
// Newton inversion cannot detect on its own.
struct H2OLiquid
{
    BRAE_HD static scalar rho(scalar T)   { return nsrdsFunc5(98.343885, 0.30542, 647.13, 0.081, T); }
    BRAE_HD static scalar mu(scalar T)    { return nsrdsFunc1(-51.964, 3670.6, 5.7331, -5.3495e-29, 10, T); }
    BRAE_HD static scalar kappa(scalar T) { return nsrdsFunc0(-0.4267, 0.0056903, -8.0065e-06, 1.815e-09, 0, 0, T); }
    BRAE_HD static scalar Cp(scalar T)
    {
        return nsrdsFunc0(15341.1046350264, -116.019983347211, 0.451013044684985,
                          -0.000783569247849015, 5.20127671384957e-07, 0, T);
    }
    BRAE_HD static scalar h(scalar T)
    {
        return nsrdsFunc0(-17957283.7993676, 15341.1046350264, -58.0099916736053,
                          0.150337681561662, -0.000195892311962254, 1.04025534276991e-07, T);
    }
};

}   // namespace brae
