// NSRDS correlation forms + H2O coefficients vs OpenFOAM's OWN values.
//
// THE ORACLE IS OPENFOAM, NOT ARITHMETIC I DID MYSELF. The table below was produced by
// dissect/liqref -- a small OF program that constructs Foam::H2O and prints rho/mu/kappa/Cp/h at 17
// digits. Testing against hand-computed values would only prove I can evaluate my own formula; testing
// against OF proves the FORM and the COEFFICIENTS both match the thing brae has to reproduce.
//
// Range 280-400 K brackets squareBendLiq, which runs at a uniform 300 K.
//
// Includes a NEGATIVE CONTROL (see the end): a deliberately perturbed coefficient must fail these same
// assertions. A test that cannot go red is not a test.
#include "nsrds_functions.cuh"
#include <cstdio>
#include <cmath>
#include <vector>

using namespace brae;

namespace {

struct Row { double T, rho, mu, kappa, Cp, h; };

// Generated by: source $OFBASHRC && dissect/liqref/bin/liqref     (OpenFOAM v2412, p = 1e5 Pa)
const std::vector<Row> kOF = {
    {280, 999.62487928454073, 0.0014300291329221544,  0.57871727999999989, 4211.0158121564882, -15934577.139513608},
    {290, 997.09779658913828, 0.0011126737698711271,  0.59440638499999987, 4193.8003320010603, -15892558.818986528},
    {300, 994.51146842130504, 0.00088614741033889405, 0.60880999999999974, 4182.9480988064988, -15850679.935920451},
    {310, 991.86272142791631, 0.00072058248924828175, 0.62193901499999982, 4177.4402009991136, -15808882.056429174},
    {320, 989.14811145249382, 0.00059698641565941789, 0.63380431999999987, 4176.3825576463487, -15767116.311589021},
    {330, 986.36389129776740, 0.00050295446547332211, 0.64441680499999998, 4179.0059184567817, -15725342.149132438},
    {340, 983.50597349484815, 0.00043018557800759852, 0.65378735999999982, 4184.6658637801202, -15683526.085141577},
    {350, 980.56988711473730, 0.00037300059411912175, 0.66192687499999991, 4192.8428046072058, -15641640.455741892},
    {360, 977.55072743231472, 0.00032743476022936729, 0.66884623999999981, 4203.1419825700141, -15599662.168795714},
    {370, 974.44309696473090, 0.00029066832134331524, 0.67455634499999995, 4215.2934699416455, -15557571.455595860},
    {380, 971.24103603494268, 0.00026066121092898937, 0.67906807999999985, 4229.1521696363416, -15515350.622559205},
    {390, 967.93794052901364, 0.00023591382489531620, 0.68239233499999985, 4244.6978152094707, -15472982.802920273},
    {400, 964.52646388389849, 0.00021530736151418751, 0.68453999999999982, 4262.0349708575422, -15430450.708424833},
};

int failures = 0;

// Relative agreement. 1e-13 is not a fit: both sides evaluate the same closed form in double, so the
// only difference available is the last couple of ulp from operation ordering.
void expectRel(const char* what, double T, double got, double want, double tol = 1e-13)
{
    const double rel = std::fabs(got - want)/std::fmax(std::fabs(want), 1e-300);
    if (!(rel <= tol))
    {
        std::printf("  FAIL %-6s T=%.0f  brae %.17g  OF %.17g  rel %.3e (tol %.0e)\n",
                    what, T, got, want, rel, tol);
        ++failures;
    }
}

}   // namespace

int main()
{
    std::printf("NSRDS forms + H2O coefficients vs OpenFOAM (dissect/liqref, v2412)\n");

    for (const Row& r : kOF)
    {
        expectRel("rho",   r.T, H2OLiquid::rho(r.T),   r.rho);
        expectRel("mu",    r.T, H2OLiquid::mu(r.T),    r.mu);
        expectRel("kappa", r.T, H2OLiquid::kappa(r.T), r.kappa);
        expectRel("Cp",    r.T, H2OLiquid::Cp(r.T),    r.Cp);
        expectRel("h",     r.T, H2OLiquid::h(r.T),     r.h);
    }
    std::printf("  %zu temperatures x 5 properties checked against OF\n", kOF.size());

    // ---------------------------------------------------------------------------------------------
    // h_ must be the analytic INTEGRAL of Cp_, i.e. dh/dT == Cp(T). This is the property that makes the
    // enthalpy consistent with the heat capacity, and it is the one a Newton he->T inversion CANNOT
    // check for itself: an h that is smooth and invertible but inconsistent with Cp converges happily
    // to a wrong temperature. Central difference, so the tolerance is the truncation error of the
    // difference (O(dT^2) on a 5th-order polynomial), not round-off.
    {
        const double dT = 1e-3;
        for (const Row& r : kOF)
        {
            const double dhdT = (H2OLiquid::h(r.T + dT) - H2OLiquid::h(r.T - dT))/(2*dT);
            expectRel("dh/dT=Cp", r.T, dhdT, H2OLiquid::Cp(r.T), 1e-9);
        }
        std::printf("  dh/dT == Cp(T) verified at every tabulated temperature\n");
    }

    // ---------------------------------------------------------------------------------------------
    // Physical sanity at the tutorial's operating point, so a sign slip or a units error that happened
    // to be self-consistent still gets caught. Water at 300 K, 1 bar.
    {
        const double T = 300;
        struct { const char* n; double got, lo, hi; } checks[] = {
            {"rho [kg/m3]",   H2OLiquid::rho(T),   990.0,  1000.0},
            {"mu [Pa s]",     H2OLiquid::mu(T),    8.0e-4, 9.5e-4},
            {"kappa [W/mK]",  H2OLiquid::kappa(T), 0.58,   0.63},
            {"Cp [J/kgK]",    H2OLiquid::Cp(T),    4150.0, 4220.0},
        };
        for (const auto& c : checks)
            if (!(c.got > c.lo && c.got < c.hi))
            {
                std::printf("  FAIL %s = %.6g, outside the physical range [%g, %g] for water at 300 K\n",
                            c.n, c.got, c.lo, c.hi);
                ++failures;
            }
        std::printf("  water at 300 K is physical (rho %.1f, mu %.3e, kappa %.3f, Cp %.0f)\n",
                    H2OLiquid::rho(T), H2OLiquid::mu(T), H2OLiquid::kappa(T), H2OLiquid::Cp(T));
    }

    // ---------------------------------------------------------------------------------------------
    // NEGATIVE CONTROL: prove the assertions above can fail. Perturb one coefficient of each form by a
    // relative 1e-9 -- far below anything a real transcription error would be -- and require that the
    // 1e-13 comparison rejects it. If any of these "passes", the tolerance is too loose to catch a typo
    // and the whole table above is decoration.
    {
        int caught = 0;
        const double T = 300;
        const double bad5 = nsrdsFunc5(98.343885*(1 + 1e-9), 0.30542, 647.13, 0.081, T);
        const double bad1 = nsrdsFunc1(-51.964*(1 + 1e-9), 3670.6, 5.7331, -5.3495e-29, 10, T);
        const double bad0 = nsrdsFunc0(-0.4267*(1 + 1e-9), 0.0056903, -8.0065e-06, 1.815e-09, 0, 0, T);
        const double ref5 = H2OLiquid::rho(T), ref1 = H2OLiquid::mu(T), ref0 = H2OLiquid::kappa(T);
        if (std::fabs(bad5 - ref5)/ref5 > 1e-13) ++caught;
        if (std::fabs(bad1 - ref1)/ref1 > 1e-13) ++caught;
        if (std::fabs(bad0 - ref0)/std::fabs(ref0) > 1e-13) ++caught;
        if (caught != 3)
        {
            std::printf("  FAIL negative control: only %d of 3 perturbed coefficients were detected --\n"
                        "       the tolerance cannot catch a transcription error, so the table above proves nothing\n",
                        caught);
            ++failures;
        }
        else
        {
            std::printf("  negative control: all 3 perturbed coefficients rejected (test can go red)\n");
        }
    }

    std::printf("test_nsrds: %d failures\n", failures);
    return failures ? 1 : 0;
}
